classifier: !!python/object:torch.nn.modules.linear.Linear
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - weight
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDgAAADk0MDQ1MDIzNzU2NTI4cQJYAwAAAGNwdXEDTZgDTnRxBFEugAJdcQBYDgAAADk0
              MDQ1MDIzNzU2NTI4cQFhLpgDAAAAAAAAZqaLPHWwTryVYGw9vV9PvXEmhr13wi09z1coPK5jCT09
              Dio9g1dtvSL2lL2QySe8r/6OvUBGSj2n/Pc8qWNEvfbPdD3DN2S9TrCMPYeVNT1LjVA9aa9zvci4
              3jxWApI9spMiPChxfj2mOSG9tqqxPFJtlD3l1QY8HWobPaNIETwAnAI7rnuAPershz1yJLq87d0M
              vXZzWr3mFIg9Sh7gvC51eD2EdsS74DYaPDcAaz2Mi6y8MbF3PbS8ubyihpY9nloKPXExory6aSe8
              GVeSvexbbr3BS2E9ikScPLLZUDwEDFA77sd/PJZvxDuRHA684pSIvS7LdLyRQC+9CtqCPHLbkz37
              XRO9R6mhPLALKTxDGQO9AN6tvJmJiz0awCc9jZUAPYUQkb3Weho9LOIYPSZXFLth9LA8ddcave8M
              K7ug1mO9ydpnvHjBCb3GU4O940hRPbC99Lx5ccI8nZp1vR9R7jqinIG99sNUvdTH77zDD1a93Aok
              u8wCx7tEVpM9q+/ivIOtC73jpa+8K9Ruvay9Uz1C09a6DV+VPY0fhj0S0/O8vihRPSCRBT2ZvPA7
              ofCfvKP387wd2o09P+1yu5KSez1QeHi9DI9UPacNQrxCzL48u5iAvQVEgL0KkNK7fjDUvKDzMD2+
              S2m96TlkPRTPvryjBom9SZfgOeiP8Lx3vsC8k5ItPdZylb3zTYc9REa1vOcIHr3OqjU9v0V9vbYh
              wTuUtHi9Xzt6vcYcgj1Rsnk8azk0PZL3xzz8XRI9pg5mPdZTe71Cmky9/36DvfKtKj1PaiS9yUOh
              vAjC6Lyo3oS8FoNgvZIIJz2fMdc86ufXvMhPj73GVxK9J2WGPT/Scr0Xgyk9YnuMPRO34TxmV0+7
              e+jUvD7EUDyUvGe9/QqfPPNWhTvccyM9qc1VvLH0kL0z3LW7FEdyu7UFIL3PTi49bCTTvCyPlD3s
              CE294ZJ9vUSOdz1Rc069/6ysvJHJRz03Uoe9/I12OxtqNz3aWuA8JU+tPFAGczwEyGK9UsQ6veOQ
              xDzw+jW5N/2uvCE6KryhmW09oYpjO2PNYr36r429AdM7PTLJ7ry4LpE92eCJPJja2zzBj8I8zXFW
              O4ZgK70fBza9X/eNPPMqKr1Ge8i8R5MuO3zpfL3Jx369AzZ1vdBuED2YE428HFZIvUq3Mz3QzV89
              ifecu3KmaT3QUXA9f8eNPTtsYz3SD/i8yJIRvVM4vDz2ECi9DL6NPQ4UBr2XTmu830JAPf7liD1K
              ajq91mFnPQS08zyRzo09ZqRBPaWhIj0Sbs68BFu7u8KyNb3acky9zNsAvVm6kr3DqHY9A58hPGLU
              vrw7PbI7gvJPvMINpztW79m8QsrAPIJ+lr3gUOu8/y47PUiDpLw5UCa96cwNvTbqHL0F8ZU8AZZ1
              PeQ+HL3grH87IRmKvVUFu7xfuZG9GfGdvIEkpzydcA89bAAcux5xk71VSRM70C+SPUlvYT32y/y7
              +6qIvJx+bT0rBDU9+E8uPLZ8pzvvUqE8l+PHPDKPtbzYMns90crgvFgTRj2BRGW9QjZzvZblCz1W
              boG72AC+vDgIs7y81iK9SCOGPcKCFj142G299P2IPRKu/zxTcWY9qEGHvQPkW7styJG9wvh5PfkQ
              RD0dqiA8qkFxulQfOT1CLOW7JJ1rvfW9Eb2J2eY83E5aPaVsjT1V+Eq9uvxDOAy11zztKgg8hJoH
              vcHZZ726XLc7BKVIPbQJzTymFfK8HlzrvOxpML12cpU8wsMBPcMWPz1pOeI8e086vOXYir15A4s9
              h77ovItlbryee5o7yMgDvaqCwzzP8JI83QQqOi53jz2Vt4y9yjKJPa05B7wa7oY9+w2TPbEXUL2N
              mtG7I5qFvdrdbzz8jN88WXh6vSK/dT3uxEE8VWblvPQfZLypNae8N2TIO2LgiL0V/O48GBo7vUeg
              zbxhUZG9fRCrvKNdiT2pMxe9dUQfPBL5Tr1PmTK9RAqEPGw8Ar1oiT+8b7Kiu1z/VL3nzn69MeJo
              vcVWIDw2OyQ9P8+WvQMIgbrWjB69zFTjPIa4gj0g0ZK9KQ/kPO54Bj0KAVe9NxZlvfEPobzB+ai8
              MgDpvOQ8dr0P10y7v3XMPOhbSj1ydSy9Sf4NPWY1R71WPXU9QFeIvLhm5Tz4sCm8qI/8PGyPkj0e
              HwK7Oj11u9l7hj2FzD89sPmOPW3WAj3BHz+9kdo3PHspcr0fczS9S+4QuyFgdrdc+Im9WLQMPSe3
              T73BcFc9j4jEvE3GC71D0TQ9evqMvXKo7rxl7Oo8lnRHvDbWL7wQmI49mEOKvc5djj1+N5a9RdSU
              PbKlf72TZr+7lTjdvPqNVL1v/pC9dVqTPfKqCD2GRxa9aGtvvTM0Uz3YO5A95O2+O1IXOT098Ho9
              wll+POAXzTxntES9BJ4FvCSGJL1YvHY9MEMjvCtfGDwasYc8ylSUusKAjDlMd3O9XOcMPckf3zzH
              AUa9oDCCPU0IPT2R1nU7i12DPfDIi71uP5m8Cg98vbIkvLwbJmK9lNCMPWPwpboedlw91sv7vKFP
              g71qrjG9CL50vaSsR73jb3u8vdsfvYp1T71sPD+9Jr24vFxyZ7yDTIi9KC2pPB+bojxsIIM9Bmmj
              PDrppzppLli8+2YbvcK9Tb2t0oS8yFKPO7/xGL3T+L28opKWvGiUi734S+w7GtwcPSq1iD0Ai1c9
              izvfvF5/HT1ZKgU7+i2JveTlW71TKEY87wPEvGtGar3ohIC9tyGHvEYr/zzBcq28ey8+vdRDWDzN
              n8g8wHOUve2JK716m3M9xLgbvId5hD3Am2i9sgGKPQOt1zy4D9m8X5vvvPgehzwsOhU8fOPQPFL7
              Cj0JuYU9wRt9vf1EeTwmvG29CowyvK2XubzQtyO9534BPfIrgD0jIY69DSACvdW8GL1H5MY7yRdz
              PYxUmrmgIjK93Gx6PT4+Ob1ToXQ9f0hgPafBXz2pqFq94okoPdM5WT3t81u9SndCve1XML1nXwU9
              ahU9vO/Kcz2CpoQ9FX6uvLc0H7wT88K8/uEjvWZMrTxr8w09c1+KPdNzhb1cwm28C5u/PBI+jb27
              1FQ99p2KPCV9hz0VRs06pvB7PUfw6zzLHpE9dTYRPd6yYL0BBUs9XwOVvY6fMD3ntVy9qp8dPVOl
              Pj1iKTS9VkhvvQGGFb2Maps7eaHTvI4NGbyeSp07JL7VPNrHirw3NGS9HoV9PThZHr3tGZC9JLmF
              vds8hj2Uk04992ZovCT4JL0jEHc9FzaFvUBxvjwaLi08mKq8vLeweL1f5GK9g209vXEDkz2+b4W9
              twcivYJzYb2cJhA9VPQJPG74Sz2OnpC9VPG8PLAeoLyKHHw8Sf5wvP7tVD3qDrw8+SnqPBnDPD2e
              8PO8rxfwOxFsNT2eW8a8njoqvSzQC73HmCy9PgIivNzFVL3WfYM9IukQvGmuVT1IJVq9DhNjvPiG
              jDzAYBK91QxMPdhZBz35bDU96ilYPPWFKL25dCQ7RnR7vZ1Tj7znmYU9ohmTvcmL9zytV8G74hU0
              vS6SLD355IG8ZT6PvVrH6bsLa3+8CVlzPeoj8jxfyzy92mErPd8bMrw2Mec8FMw/vSBTfbxZXpG7
              sbdoPWU2Bzz1OhA9AhfhvAdQ8Lwq3Ya9kha6vK6fqrvN+yi94DGVvQ6VLD1TnNC8IJaUvET2AT3d
              4HI6jEsnvX/nkD11T5U9vbI/veEAirw9pV89weq2PCcQgD1oSz89eTGkPBQv/Twttdy8OyaMPQl0
              bD1bW1c91kKjvNzflTvnaYw9Pk2KPVZ4tzyzdCG8VlfVPF7YHz1k5oa8h1Jcvf1wkb3ze628A7AU
              PQXsEj3uwn69I0UkveTS37zEWWm9SSEsPXxVlD2Twxm9RbWjPHFdILwMstY8ApUhPVsnlTxtemK9
              e2PIvE8GHz0/iGm92gzqPLhfjz0dILu86w5GvQ+qfj0zgZU9lq4mPI5iDr30rXE9XixavYgPg72r
              zyQ99vsxPUNClD2vpok8AbVBvSoTMj2quw69Bx0svbA2t7yjIBw9yYmHvUgghD2x7i4956zcuyOG
              pbz7GYo9CIPbPMmr7TzcNkM9q72VPfoRDD38Dm49gov8vOGQHL3EP9C8IkBAvWu1bj1tOIG8zbbz
              OwnDozxRImU96mWUPUDoZz3oI2E9wAP8vOa6Gj2GBoe9T78BPSpOT71QjjC91P6dPEbpgr1BNgg9
              9s1+vaBacD15i6c8b9r2PEJDKz2k7ak7dJtMvJK7AL0il7e87mtwPdbiwjwfQCS8jYypvCVIfD1n
              L6C8mKqWu1CVbL0x/Ys901ePvXghFb0rXZM9T1+RvRj8eT1M6oe9Qb/KO+xFdrxyz0+9X3SIPSvF
              BLwX1s48rACsPOVm+rtU1zg93QyOPCSqjT1mFF+7nLGAuiVlIDxT9BS93tZZvX69sLzgrKq8qluK
              vQSQ2LtmoNm8/cqNvWxnrLujQny9NA3lvGs1ozxicha82uExPWt2Zr33tv08U7R+vWTikD3bmo29
              gEGDPV32hz2CeHy8HMctvSaAPD0hiWw9vyy5POEYhb36BD28CyPSPClBlj2DHoK9GIRove/puLzY
              CXU8UwonPd6Piz0yLkg9Tg8VvUPTTDyuBSI9p1HhPCEYmzyqsqA6mZAWvd92BT0iEju9OzODPTsK
              Vr0DSR69Q6h3vW0d6TmX43K8iQnSPEi4jz1b3f08+5soPVNWxztL/Cc95GtZvKB+TT2NLpA9I6V1
              PCSuzLzjLDY8/TpyPTLhiT1KECY9kXD3PMoDjr2PfMm84XdzvPzsEr1L5Ru7y+tjPDl2gD1WfbG7
              D1skvbqdYj2f/I099f+FPWQs7jy20SI9l7doPYA5ULzZ+Y89vvbZu5gTeb1Uahi9stiGvT7iC70=
          - 0
          - !!python/tuple
            - 5
            - 184
          - !!python/tuple
            - 184
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
    - - bias
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDgAAADk0MDQ1MTM4NjkwNTYwcQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQw
              NDUxMzg2OTA1NjBxAWEuBQAAAAAAAACtM8I81YjJvIffX73E9XG8A9gLPA==
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  in_features: 184
  out_features: 5
  training: true
encoder: !!python/object:torch.nn.modules.linear.Identity
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: true
optim_hparams:
  lr: 0.0001
  lr_hparams: null
  weight_decay: 0
