classifier: !!python/object:torch.nn.modules.linear.Linear
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - weight
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDgAAADk0MDQ1MDkyMTI4MTEycQJYAwAAAGNwdXEDTZgDTnRxBFEugAJdcQBYDgAAADk0
              MDQ1MDkyMTI4MTEycQFhLpgDAAAAAAAArDZ6PRwxN72UIoy9RHgQvPWMQb0wqLW8K3t6vYsFgLzi
              U3G9ooNFPRf5ar1jiA26nqYePYEULL3Bdj094cHkOhcgMD1qHPe7L0K8vLIhNz2KgYk9Od0PPVjb
              X70CkFE9BMQgPXVTNz3nbLi8K4xjvaXRbr0KtiS92+kPvfXndzx3yOe8t4aePC7PWL19/0a9fSnY
              vJNFerza00U9rcYFvK4kTzxCmXy9ZtdyPQ7Rkb032tm7Zf6MPZFHN7toJoa9Nrq1vAJ5jj35L6W8
              AT8VvC5LT72+eLs85MVTPZdrp7zLhYM9u1UZPKybc7wf/3O9GtBJPEp8zDzLL408e49GvWxKWbyl
              VHs87kz+OFMWaD3b8W+9uOFdvdwaf73dXRq9qVcKPVuc1jyFD368qiiJPZ2fh71pknO9TLn1PC6h
              IzymUIu9b/IsvR04yDxgaoK9HW9qvZOwlDwzwei7u8dNPRgKa71CkxI9IKN9PdufQT3e0AA7kSb8
              PGaEE72COZo8nPqHPT+xeT0iXBk9q3yVPKD8ZD2dnIg9CiJxPVkWIr1BPHQ9y7dhPQJ2Uj0wrki9
              eX6RPJSrFr0Zd7g8imIWvRAsfb1JpVi9aFqSvaZcAj1YcgO9WvlnPWcFJLzpyQe8QsdePQ2xlr1Q
              P0w9VY5fuyTper1tRW69edu3vEJPgjvxPdo8qyQGvedaIj3eNIu9SGCEO2VX0LykRCg4TmREPZrw
              gTsI28A8qHQ6vZ/8ADwI3RW9AoMTvWtEMj28Vzk98MxPPeYotzylQnC9IzFyvWH0ubyazZU9td6A
              Pd54j72Q+2O93/OLvdPiUb2klOe8rnNWvFLOOr3GW0g9XzXCvGvgOjwrmgk89tt0vR2Dbj2/1e67
              2alKPWCSdb0N9lc83LPxvLuZ+TyWgmO9ykxuPbS1VDteUpK74etUPWpdUj14Apc8DhuBPbeGrLwK
              DIw8QlUzPTEZdL0qsqq8jI1yvRTA/zyUBda7R9WIPa28kL3I7OW8TkP/vKY2lrzj+fM6CdYMvXwM
              h7v3k4c8uCjAvBe74TyYtR69S0TIPN9Caj0sGme980pRPVlIPz3XlcY8vyWFvaqNI71EZy69nFOx
              OZxnmDz+jnO7EbEju9KRKr0Fse08IYslPEPEkj3OT648Ds/gvAEiLL0jkIa99a2WPR2eOL1IBb+8
              ltshPdUhEb1AxyW7Zd+Su2rekj0VDvA8vimOvfxZnjtP/R89eqCDvecaj7zypXW8DcvTuy36i70w
              FOo8whj4uxPE2jx4tU48Z0IePcxxRLsEPSc7LN5YPUz+jjtSD0I9bMODPfJVbztIEzI6Xtg0PF/q
              kz0E5Ps8AtiFPQfXt7ycVym9Jy1HPL00T73wVvA5SHiSPW88WT1UxyY9Kj64u+OCnbwjHn49c8WT
              vY0FSr1FLxO8BZlfPFBXZbyx9so7iXcMPf3curyPV5O8B/PhO7w4Tr1AsI69GmXMPKn8gr1xVTG9
              8vGPuxewDLsJdii9geQhvQvINb3iUey8qV9Cvfzsbj16wbS6Fqc5PZwBGr0gAGE9xsCSPXns37tz
              9Tk9Y3mMOgXzDjyTuY287wE/vZzohj2sloA9Pl5JvGDX1Lzym4W9y1oKvTcE5LxpXzm9gAwIvU/F
              Zj0xBau7YjS3vL4LQz10+YM9CytbvDkslj2ZPLO8BNWOu55ekz3o5oQ9pzuQPZXuSjxBwNK7G+rA
              vDeyAb3sJJq7nid3uzTMDD2S84m9QbJ2vCfUBr1d1ji9b+cAPRt6A71jRDq8uWaUvYdtlL3oewk8
              BGcVPZJdkjxV1Sc94nPfvA3GnLxY8k49Pw9AvCDzBrt5oFS9OntnPVhfJLuu+R89yUVxPc4yujwQ
              ywk96AeJPbynhz01PB280hJTvWTpOr1aF0893hXNvIH/Vb1F/zo9mR0vPW4ZgL39YyQ9II3rvBRI
              e71aMEY92Qm7u4jXo7wE5qi79eQvvFdolj3z69O8Tl6WvWUdPb3SaiG9Rl9/vYqLHT2X2NA7OHeG
              PeHcQT3qL+08lqhrvRN/Xj1ijhy9XzRGPVBVV72pF3Y957wsPAc1Eb3ReJo60Q60vKbllj31+wK9
              4uYHvRQxvbxQm6C859/IPIDMoTtyiJG7mthUvbHfCr1zFCw9g+KBvTQmS71S2U29CB2IPTQ8Vjzl
              +xA9nVKFPT3UeT3uUS89l36UPTYxBr2K64S8pzvtvItyIT1FUh8914DWPO0yD721XUS8WiuDPYA1
              6LxGuBy92ryEvfwJcr2tCkq9sbu4vC0s8bz0UMS8BLhNPcNOJ738GWi9tNFHvfqzhzvDDyY9HipT
              uZNyir2Y1lS95uzfvBklXj0Kjbo5e3yzvHFFgb26H+67mCQQOX0YGL2NtVE9tuM0PU//CjydWaS8
              54qUO0Q9SL12Zoe88/NoPaIKWb2FEB+9SaqSPev8br35SC299PgovRayPL0Wp8s8qbVuvbWIej3a
              ewY9Oro9PdbHALwCI2q9qAQKPVxZiT15PI+93kNAvbS+wLviKHQ9i4JnvRQCNz0cRCM94WSiPHJ5
              Dr1HEiY9fwmTvSmLPr3G/is8h/VnPZwAKb2sZm89VoJ7vd86kr3jgYy9p7yWvdZFD72J6zQ8nkeO
              vGXexzxLjH49c6c/PY6pFb2yUnE8Rn1rvUuMjz0gwJW8mF9tPQ++i73135k8r0SKuVuIPb1THx09
              RjX8vIxrjj0Nohk9v3fTvNYTRTszpQK901SEvSIwAz17kwQ9RorlPLIlij0J8iw9wqaTvQ5/Kz3t
              6JA9LE1rPYnMNL2qd9+8eIQpPadAULrbUQI9FiJSPWpbwTy8P4o9rDiVvXdptrw3tB88nIWLvNaw
              Fb0PJHg9qbSIvRZY0rsrhIY9BtNvPblzUr2ZPVo9QW7+uwITY72SE5Q9gCz4vDcpOzyCdO68irGM
              veP9FD06mFu7KQhfPMnyjbxtS2U94iJrvWIJAT2YmRi8a5KLvdTVfD0vk6U8lWbju74DpTxsRF49
              WblYPZhxUrwipdU81zHrPCYoS71qMSA9yqtgvXMBeT1Mj4i96IoMPYLbA73VWP+77MXQPE7yQ70z
              wgs9ulB5vftqkr0sV7k8sDKpOw6KSL3h2YC9c0iDvRTYC71izX29mNVXPVzWwjude9080rOEvcmC
              67nj2pK9f2zCu7shkb2G3A49cuSQvVigPL03Ggk9GkxFPSAKib33Zwk7uM79uhQLiz3BZI89Uip5
              PSeGHDuatI49k5MRvHGwjD3o5Vm9JWdQPTbmpbwWioa9TDmvvNzYAr0ATrI8fowXveCxgj3KqJC9
              yG+NvK7agj2L9ei8dYaCPH57W73SBmu8IGs6vDs09bur1Dg8hnNrvbTmZr3Nq0O9Jh7QO0Wqtbxq
              ykW9Fv1PPBTdtrymXts8F9gdPToJOr1g75O9H7IwPCQjFLwgD2Q9I/qzPNo8d7zvMta8uluJOqQ9
              hryjbdG8BliNujqSID12ncM8INeBvSPwM737pEE9yIuTPclyNb1e0rK6gU6Kvdt2kjuJ43u9gsl8
              PdfXPD0BP4O9WW0NvcZzUTtqze68g2pMPYlEjj346OC8eFZ+PcEIxjyzfe88/UNLvYvyRr0KGYY8
              VdPgvP2enruP+5I9QlXZPB7Z87xAyIW9yquHPTyzFD3n8+08pIPWu378OD1/nYI8Z2WcPBe2Ibxj
              OzA9aVzGvBoBIT1WAYg9KRskPZARYz1YaW06kg+9PBTByjxqqCo9myGfPHQJkD3hCmg9/EYSPQAI
              Qb3RmI87LghXvYu297zSpQg9PwB0PW3dY71pc5a9aTCrvBFZJD3rzYA5PLOuPET+dbxdeu85Kb9Y
              PAhDZT1FWR29MSuFPbbNhb101Xs9+d2OPZ2uA7wwDrm8iF5tPQ7Ekz3F1CK9x/B9PGiehDyVJn29
              EDEEPWUalT2o15K9wwJlPcZ/tDwWUIw9zFkdPVKAhb2Wz2q9LlhgO3tcUL2DTrO82Y1uvc24Rr16
              oiY9pUYuva5VlL20Zgu8adG7PJO5bD0NWwW9MXdpPXjpFj37bxe8iK4CvTqEqDytq/Y8UcoaPH79
              fL2JXwY8wGgZvNX3fL2LAYO9ona9vKcSbLyWrcQ7PLlkvZeKA73ijwe9UuiNPaczKb0rgkq9Oecf
              vd6H4jrkLwu9Rwc9Pcyocr2jeyo9BgWQPAo9f70Awtg7gHlevY1fYDwoUEi9KZ5sva+RJb3BtBU9
              tRDuPOOSQj3z8Ce9jctEvVsaOj2PR3K8roR/vW6eIj0UOS+92GdnPYLilr2JSJ08gxi9Owozgz2R
              9WK5QM7QPH5RHT2u7eu7xHdevciqS719yxw9NAdCvQ2PHT0/8Pg63ZcMvRYNAr2GTwq8BpRuvJ5Z
              bL3bjmI9T9Q8Pb2VTb2iIuu8+iBTvANBIzxK6pA9TcNKvdpW/Tx6J5U9hlQ6PY5neT0Thsy88kBE
              vfI+hzwLEjg8AE2KvQ8lNL2W6JS97lULvI2eKT3Bqhe9VpqNPe5nTT31/tu878eTvfFbkL24DDC9
              PHpTvRQ+Qj2cZ2S9otuzPEcnXTzAgQi9cWw4PT/JkbzhKny9KXAivFumYbxt0Wa7zjHXvJ2cDzzu
              qfS8KRWUPSaOKz1J1r28/86kvDgmR7xW0ZS9jQwlPDHigb17wQS8mURGO5HjkT2aJZC9fPxZvSJD
              c72pJPk8qxx/vYSuyzxTUMU8Y908PaYNYr19VJ87NOLgPKsTDT1QAnw99CiFPXhpID0hDyg9bhEF
              Pfkjvbwf8gg9DSpkPNm2krsNdL68JrFQO+b3Xb0JH4Q9NQt+PZPj7Dydl6g8lJU4vdQlYD1yN328
              JVUhvb4WxrvvyBO9TRVAPZ3Ekr0GCYC9k0eTPQTpNzyBMHm9jYuGPVHWhj0PT4C90USCvaidET0=
          - 0
          - !!python/tuple
            - 5
            - 184
          - !!python/tuple
            - 184
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
    - - bias
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDgAAADk0MDQ1MDIyOTk2MzA0cQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQw
              NDUwMjI5OTYzMDRxAWEuBQAAAAAAAADwYtg8mYCHPdcdqTzeJwM9PM37vA==
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  in_features: 184
  out_features: 5
  training: true
encoder: !!python/object:torch.nn.modules.linear.Identity
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: true
optim_hparams:
  lr: 0.0001
  lr_hparams: null
  weight_decay: 0
