CHECKPOINT_PATH: checkpoints
DATA_PATH: /esat/biomeddata/SHHS_Dataset/no_backup/
MODEL_TYPE: CNN_model_supervised
accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 64
benchmark: null
check_val_every_n_epoch: 1
data_split:
- 3
- 1
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
first_patient: 1
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
ipus: null
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
load_json: experiments/1D_CNN/config.json
log_every_n_steps: 50
logger: true
max_epochs: 20
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_hparams:
  conv_filters:
  - 32
  - 64
  - 64
  hidden_dim: 256
model_name: supervised01
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_patients_test: 100
num_patients_train: 500
num_processes: null
num_sanity_val_steps: 2
num_workers: 12
optimizer_hparams:
  lr: 0.0001
  weight_decay: 0.0001
optimizer_name: Adam
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
val_check_interval: null
weights_save_path: null
