classifier: !!python/object:torch.nn.modules.linear.Linear
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - weight
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDgAAADk0MDQ1MDE5OTEzMDA4cQJYAwAAAGNwdXEDTZgDTnRxBFEugAJdcQBYDgAAADk0
              MDQ1MDE5OTEzMDA4cQFhLpgDAAAAAAAArrOUPTpTgD2KOwu8TqEpvTmaIT2AiIy8s7kvPcCQRr0Y
              TNE8x+OSvZH2fb0ovW88n19YPBhYJr0GGau8RtB8vHc6DD0bvGW9KibavGnQhT0ARla9mvkzPUjE
              Vz2KdRA86xB9vSzJB73xyFo9ugc5PTVvpTxRAPA8f8c9vV2tBL1axsA8XSFhPLWiiDylRFa872o1
              PWhokL2oYj+9xp/PvDhBHbwc62s9ZiFdvYeigr1/75O8HrnTPPBgDzw/aHS8z/PkvOn5iz3X1/A8
              oh4pPNBpWD0aXZM96q2RvYf+Uz1VUk49he5DPTBITj2jvYk9mvVIvRt/WT2IpoU8B+wxvNPMCT3v
              ABE98IBlvQTsRD1qNs08/wXlOn4AIr1TvYW96bQjvUj0czwY/rk7VBggvYsyV7znhlE8iKCDPeKg
              bz3crI08rD1tvVINhTwxQ3S9w8CFvVkYCLwzomG9QMhaPfRLebsFIaw71OaLvQYcID04w5q8eWet
              PP0TYL3zq1G805A4Pd3blb26kxo9fZQAPDR6JzsaE/g8YpkfvBvZhr2D+Y49xfdWvRA9Rb2+fOG8
              m15KPC+Lcb067em8dw5VvD6iij2Uwxi8JbHuPKnTKr2Bcz89t1WHvbKBfj1OfeO87khDPRk2Zj3T
              nRG93ZyUPRPJMz2bB4E8Gu+tO9Jxory+Ekk9NpayvKElhbxIk1U9/k4gOpCsJTvcrmS9anckPLeb
              nLyaSYQ9+lgYvJ4fzTxjvza9BqaEvWCPYb0Y54o8azgyvctsy7vYp9S7J61sPcXVwjsKa0y9AxCA
              vaISerxqt0W9U9+FPc8zqbwmCWo9IqAwPaiPzTv7OWM79gjAPDJxaj3aYwo9gIoyvQu6hD2tV1E9
              bIBpvXM2HL0vjf28sEaKvf+BmjyDyoQ8/FGQPPKMyLySVrw8d8qsvJJtir3M8em8tZ6Iujr/H7xX
              r6K86pfMvIWFSD2ugmm9XJeMvQRhuLx0vEe9JXFPPQ8Ler2rGV09OOdIPGi/eDyTNa88YJLGPFsL
              Lj3s1mw91UHQPMfSkb1mUgy9oF0zPK5BXb3bl1I9XYcnvFPei71ooHi95ZhTPaK4ULw1UZS9mVuL
              PQeMwzyCD7+8ssGJPb0Lcz2QgEg9Qs2lPHmkBLmLiCS9l2C0PJ26Kr2iDIu99TskuhjLDT2Mo6s8
              o/+PvdvQaz21ySE9I8b8PDGBUb1k9P27V2B9PaI/5Dyx24e9A/WXO473M7xljYC8JT3kPO5bMT1Z
              h3a8VMzNvEhlKr3mPoy9kWgPvKhXM7sCXl29NaMFPdEbND0AcyI9poFpvJ4MLD2xKKq7dCRzvR3f
              Bb2todc7oLUdvfmXqzuDh7C823OPPURFgz3hreq6tPWevLOcdL1m8os9NbOJPS05Qr1kOVy9R+IN
              PbOMOj3NtVG9tU0wvRIZA7zU0Gi8+pugPPc1wTyBACi9xpcGvSuXDz0Jgc48Fg4vPTwAD731R3S9
              qdZ0vWpPqrygvKe8DOnVPG0SvrwWNWG9zk8Zve6GDT3Fxuw8WYx6u5r/PD02tCC8J5aOPXAycr0J
              FR+9y14cvQiOY73ioJ88OIFhPW23Vb1n6Qg9s+SQvWtaqjzRjYO9/CXUPAIVMr0WKmW9s2B7vOjY
              ib0FnnY827anvLJFhz1u/zC96hBOPd/2aD1Z5uG7VUC6PF+JkD2k/h49A7knPPAjAr2WCzC8uWko
              vKMdRrzwyBk9NamRPTO4lb13NQe9Hh+QPcnKgT2pxfu6BWNYvV74jTuRcfU7hi6OPfkAObz5/Vg9
              CU3VPNVqkT22kLm8T0+RvSA/bj25/z49vXMHPXgsIb0q3hU9rUNLvXmzuDwA5fm7xuYHPBY+HTwY
              dxU93ViUPOWY+7x51YU92pdvOwYJZz1LJvc5dS2QPex+orw94a48bCYdOmcsBT3inRW6f4JivWF3
              5btBWUK9fGcVPWFUdLw3s0m9X1ZxPTYENr0pjIK9c5vNvA2CRLwspCk9bavTu0Ddjr0oPBy9bNkU
              vUXf4Tu9mji9T+ABvZ547jycneQ89RcaPTLv6ju+6kk9HCl6vYVYkb16JFE9OA54PR4Nlr2rJBc9
              yba1vBWFdj3YBGa9SUAEvQ4gBb2UP4q9TO+XvNiygD2lnIa9pUMmvWie1bwzACE9DGl7PW3eRL00
              cte6IphWvbNgkzvvv4u9exOqvHuLEr1Jr4E9gUmDPP8u/zwqh+08nOKju+gC37zFgkK9CuhPPKTk
              Xb03K3K8CkCKu2UtZz1QKxK9y9ajvO64QT0pHGM9An/hvIMmSLzIHw49T61SPEd6jj1HX6e89rV1
              PZq4bT0KzQa9sqGjPPK6Yz1ucvs8ymrTvBftFjzQ+Yu9O3f9PBcIlzzJ/II9bwRgu5xMprte7iA9
              RF73PJQSWb2/spK9pgbHPPY5Ur34hZI9eE6LPXJmkLz/zkA95LSCPUjcNz2CppM9EcRAvW+XOryu
              SvU8uQOGPcLpZbxr/FU9/SEIvRzT1zywS109wDwYvd8guryPwP88BrMlvcY2LL1aJzI9CBkBPYcD
              YT3zg3Y9nhNCPSN/kz3AHv28yo5bPT6v5bwO1X48Ja52PdbLULzeN1E9clyqvKH9h71qSy89llEB
              PeX2G71NR1M9jeH+PDMZBT3DbSW9Lk6JvPaEYTv35dE7/7NJPZh8Rb3r7oE9GsezvPeEJz30Rh89
              GoRivZsRkD13HLo8B+CjPDBQk70i6lq97xsnPanTij1cq5E9woVuPayrET3H/II96YIzPVHMfz2V
              O4c99GDDO8UJKTz7tYu9lw2QO5IamLyXIgM9JkN4vP45hT0/SSI9j35CuiYY0zykopU9FKNCPciv
              iD38dJW9SVM9vWJCE72CMdg7UH61vG0oPztTBt253uilvFttlj0BTXW7u0zqvNvClL2JAW09KzZ+
              vbDxCD37Gom9yD7NvC0kST2Nz4s9XDgsvcTkCzwXFxq9lwYGvJe1QD0JK0u9xJxjvFovLbtAi4a9
              /1wCvUJ42TxJaHG9eiKVvWGjbb1pod68UKx1PVV8hr1+QXA9GRR4PX7I7jyzclA9tHGtvN5JNj1T
              +5Q96n+UvUS5dL1kA1A8qlKyPEY2iz3qmmO9mWP+vJ12Ez0YwFW9wgw1PcblnzxVVCs9WDMFu4Nr
              I7yety88BzIqvcjTLL2GPFC6Z5tZvLIgJT1v2sI8gavkPDN3j7lGfJY9K9ktvDolfz2/PAQ8fWGi
              umP+jz3Koy+83+nlO7/ZkD3GVjw9YR8ZPQtGAjt7HdK71VzZvGtMAL3LDrA8t3dWPd6MxbziRII9
              NeeXvDhvTTy/OsQ8ucu5vFlKoLvAmHU8HeGLvUGlAjx2d7S6SjCMvd2Uib2Oyn287U2bPG8mLbzU
              cEQ9t6w7vTumybuksgA8CiGivNbr3bxuGL+8gu9/Pd6cYL3Xc7Y7fZJCvco5Vr36Fqc6cnQRPY/n
              Q70W4Dc9IBZJPVnJWr3y0RG6ui8IPYv3eDyt82A9bwRgu9+un7tq7Y88j6IkvSm+U710ha+80RgC
              PXe5AT0luiM9yS1OPUUvijyA8A09+yOAvYVlH7yS/bs8ahvlvI8bAL3ZhbG8cKzFOj3lazxCMTA8
              syeXvOn3kTt/uYo8P2NUPWPZ8Lzspxu8TdDGvOdiXL1ebXU8Uf5vPVzjPDzxsE+939vju0q/UT3d
              FJS9YgZ0vPY+DTxeJMC8KtgMPcLRoLx1Fog9Su3UvOynwDvnE2i99KDKu3xQQb3XO2O9hRQTvfe8
              szxH8V49otKUvIaSU72WBbg83QgevQ0vcz0QGqA8f04GPU24Tj3y+kK9DpLaPPTnjL0X7Bo9ETBG
              PKfpJ73hPm89to0bPARnJz2Q5JW8GtJcvefJP703tJE8Xl98PMNKzTwOZbe8dHoWvfQEAz066EU9
              naWIvZu0OL1g7QY9/QLYu2NqRL0sbk49WeqHPHMNprw81w49v/hpPRXTRj1XB0y9JBpEPTasxjyC
              QXs9UCegPH9Rib3trYE92JLgvBpDAj35dGq98I8ovSMoIb08FkK9d3lnvXqaaT2K/fK7cyGUPTd4
              ZD30FH298lPMPCXojb1FgYk8/YgkvYWQib29sII9CM0RPdooHj19zzO8eIIBvR/AqTw6LUY8v6Yv
              vVI1dz2Rk1g9CO0nvU64vDyVQXO6fhyXO3HXKT20EoS9AxuTPfH8g7yexxy9CY1cvZwSJD0Ej/E8
              WUqqPKaKiTz1oUi8NLlevLPTFD0e6V89g/x1vdWcpzyoU4c9N9OMvGSwmDyyaXE8vmeIPXtBQL2H
              6gg81NX1u/jRWz15agE9lysBPaZZlrxN9WQ9FU46PQ42Ejx3T0g9lmcjPZNgl7ynyRw90tX3PDWz
              d7z7nj+9Hx+Lu8m6ubyngGk9520bPd6pjL3SxJE8P7YjvY+cIr3B4pC8nZLsvB/MSToSFic9ql+B
              O4UxNr1epLI7ydrUuzWRiL2st5O8Yo35PA4LH716ujY9PbCVPMSJOD0lgHq8g+sJPRmCxjxROoe9
              R6yUvZHvbL2lbS69kRSEPB8OA7uJ6rG8lL4xPCnd+7wfJoy99amnvJB4Zz3GGI+9d8DVvGy5zLrQ
              o5K9UFpMvZKVJb0/Z0i99FUFPEGlKr3vIFk9lEBqPdb3U7yComU9hb2Tvat9j71Q9gu8picoveQa
              s7zVTJ08MLFzvdDn9ryAxmi9B46EPayfLLxdoJK8g5WVvQqtjj2uVq68GkGDvO5n+juBRpA7NflY
              PUqwSr2PEQE8v0YevAtNWr1qY1S9cK8uuyzb/zuG7fI86I5zvYYshb0VsxM8h1sNPSCH7brs0JI9
              lz68O303hL1bLns9rbsSPF2hbz1Wm0I924GOvAeHcb0V0jI9Yl2NPeRygb1VAPW7cnsZPQUbrrw=
          - 0
          - !!python/tuple
            - 5
            - 184
          - !!python/tuple
            - 184
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
    - - bias
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDgAAADk0MDQyODk4NDU0NjA4cQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQw
              NDI4OTg0NTQ2MDhxAWEuBQAAAAAAAAD/tPc8jk9nvZqpOb1MKfK8TJB0PQ==
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  in_features: 184
  out_features: 5
  training: true
encoder: !!python/object:torch.nn.modules.linear.Identity
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: true
optim_hparams:
  lr: 0.0001
  lr_hparams: null
  weight_decay: 0
